### ISSUE TITLE
OpenSSL::Cipher::CipherError

### ISSUE THREAD

**Issue by cristian-rivera** [ankane/kms_encrypted#12]
Hey 👋 , I'm using the latest version of your gem and everything works but I randomly receive this error:
![Screen Shot 2019-04-03 at 9 32 09 AM](https://user-images.githubusercontent.com/15311062/55482906-7e8b8f00-55f3-11e9-9eeb-08ae03b62109.png)

In the model:
```
  attr_encrypted :name, key: lambda { |transaction|
    return transaction.kms_key unless Rails.env.test?

    Rails.application.credentials.dig(
      Rails.env.to_sym, :aws, :kms, :transactions, :key
    )
  }

  # == Extensions ===========================================================

  unless Rails.env.test?
    has_kms_key(key_id: Rails.application.credentials.dig(
      Rails.env.to_sym, :aws, :kms, :transactions, :key_id
    ))
  end
```

**Comment by ankane** [comment]
Hey @cristian-rivera, can you add the stack trace?

**Comment by cristian-rivera** [comment]
> Hey @cristian-rivera, can you add the stack trace?

Hey! Thanks for the prompt reply, here you go:

```
OpenSSL::Cipher::CipherError: null
  from encryptor.rb:98:in `final'
  from encryptor.rb:98:in `crypt'
  from encryptor.rb:49:in `decrypt'
  from attr_encrypted.rb:240:in `decrypt'
  from attr_encrypted.rb:329:in `decrypt'
  from attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'
  from attr_encrypted/adapters/active_record.rb:76:in `block in attr_encrypted'
  from active_model/attribute_assignment.rb:51:in `public_send'
  from active_model/attribute_assignment.rb:51:in `_assign_attribute'
  from active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
  from active_model/attribute_assignment.rb:43:in `each'
  from active_model/attribute_assignment.rb:43:in `_assign_attributes'
  from active_record/attribute_assignment.rb:23:in `_assign_attributes'
  from active_model/attribute_assignment.rb:35:in `assign_attributes'
  from attr_encrypted/adapters/active_record.rb:29:in `perform_attribute_assignment'
  from attr_encrypted/adapters/active_record.rb:42:in `attributes='
  from app/jobs/transactions/import_job.rb:31:in `block (2 levels) in perform'
  from app/jobs/transactions/import_job.rb:30:in `tap'
  from app/jobs/transactions/import_job.rb:30:in `block in perform'
  from app/jobs/transactions/import_job.rb:28:in `each'
  from app/jobs/transactions/import_job.rb:28:in `perform'
  from active_job/execution.rb:39:in `block in perform_now'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
  from raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from i18n.rb:297:in `with_locale'
  from active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:46:in `block in tag_logger'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from active_job/logging.rb:46:in `tag_logger'
  from active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:38:in `perform_now'
  from active_job/execution.rb:24:in `block in execute'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:83:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:22:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq/processor.rb:185:in `execute_job'
  from sidekiq/processor.rb:167:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from raven/integrations/sidekiq.rb:9:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:166:in `block in process'
  from sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:108:in `local'
  from sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:43:in `block in call'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from sidekiq/rails.rb:42:in `call'
  from sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:243:in `stats'
  from sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:73:in `global'
  from sidekiq/processor.rb:125:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:124:in `dispatch'
  from sidekiq/processor.rb:165:in `process'
  from sidekiq/processor.rb:83:in `process_one'
  from sidekiq/processor.rb:71:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by ankane** [comment]
It looks like the error is coming from attr_encrypted, not kms_encrypted.

**Comment by cristian-rivera** [comment]
> It looks like the error is coming from attr_encrypted, not kms_encrypted.

Correct, but the stack trace shows a `from active_model/attribute_assignment.rb:51:in 'public_send'` `public_send` to what is the `kms_key` symbol that is being used, so whatever `kms_key` is returning is throwing the Cipher error in `attr_encrypted` 😄

**Comment by ankane** [comment]
It's still not clear to me that it's an issue with kms_encrypted. I'd try to add some logging to see what's going on.

**Comment by ankane** [comment]
Cleaning up stale issues. Let me know if there's any new info
