### ISSUE TITLE
Spec failing with ActiveSupport::MessageVerifier::InvalidSignature

### ISSUE THREAD

**Issue by antarr** [ankane/kms_encrypted#36]
I'm trying to update my test to work with kms_encrypted. I've added the initializer as suggested in the README. However, my test still fails.

### Error
```
Failures:

  1) Verification validations validates presence of phone_number
     Failure/Error: ver = build(:verification, phone_number: nil)
     
     ActiveSupport::MessageVerifier::InvalidSignature:
       ActiveSupport::MessageVerifier::InvalidSignature
     # <internal:kernel>:90:in `tap'
     # ./spec/models/verification_spec.rb:43:in `block (3 levels) in <main>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
```

### config/initializers/kms_encrypted.rb
```ruby
KmsEncrypted.key_id = Rails.env.test? ? "insecure-test-key" : ENV["KMS_KEY_ID"]
```

### spec/models/verifications_spec.rb
```ruby
RSpec.describe Verification, type: :model do
  describe 'relationships' do
    it { is_expected.to belong_to :user }
    it { is_expected.to belong_to :voter_record }
    it { is_expected.to have_attr_accessor :verification_pin }
  end

  describe 'validations' do
    let(:user) { create(:user) }
    let(:verification) { create(:verification, user: user) }
    let(:rec) { create(:voter_record) }

    it 'validates presence of phone_number' do
      ver = build(:verification, phone_number: nil)
      expect(ver.valid?).to be(false)
      expect(ver.errors[:phone_number]).to be_present
    end
```

### spec/factories/verifications.rb
```ruby
FactoryBot.define do
  factory :verification do
    status { 1 }
    verification_doc { '' }
    voter_record_id { 1 }
    phone_number { '123456789' }
    verification_pin { 111111 }
    user
  end
end
```

### app/models/user.rb
```ruby
  has_kms_key eager_encrypt: :fetch_id
  attr_encrypted :phone_number, key: :kms_key
```

**Comment by ankane** [comment]
Hey @antarr, as far as I'm aware, KMS Encrypted doesn't use `ActiveSupport::MessageVerifier`. I'd check out the full stack trace.
