### ISSUE TITLE
Can't make kms_encrypted work with 2FA enabled Amazon KMS

### ISSUE THREAD

**Issue by zoras** [ankane/kms_encrypted#4]
I get this error while trying to get kms_encrypted column

```[ruby]
2.5.1 (main):0 > u.email
  Generate Data Key (1871.1ms)  Context: {}
Aws::KMS::Errors::UnrecognizedClientException: The security token included in the request is invalid
from /usr/local/Cellar/asdf/0.4.3/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.21.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
2.5.1 (main):0 > exit
```

```[ruby]
add_column :users, :encrypted_email, :text
add_column :users, :encrypted_email_iv, :text
add_column :users, :encrypted_kms_key, :text
```

I tried following the guide by adding encrypted fields and renaming pre-existing `email` column to `protected_email`, exporting `AWS_SESSION_TOKEN` following https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/ and/or adding them to `~/.aws/credentials` or `~/.aws/config` also didn't help.

Anything I'm doing wrong @ankane ?

**Comment by ankane** [comment]
Exporting all three env variables as the article mentions should work (be sure the access token and secret are the new ones the API returns, not the ones you make the original API call with), as the gem just uses the official Ruby SDK (nothing special). However, I wouldn't recommend MFA credentials for a server, as you'll need to update them daily. If your infrastructure is on AWS, I'd recommend machine credentials: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

**Comment by zoras** [comment]
Hi @ankane, thanks for the reply. Exporting all three returned env variables did work, I'll try out machine credentials method later (thanks for the link).

I also ran into another problem while encrypting `hstore` postgresql column with `kms_encrypted`.
Following this issue, https://github.com/attr-encrypted/attr_encrypted/issues/169#issuecomment-258400208 it should work with `attr_encrypted` but I can only encrypt and not decrypt with `kms_encrypted`.

```[ruby]
❯ bin/rails c
Running via Spring preloader in process 28642
Loading development environment (Rails 5.2.0)

Frame number: 0/30
2.5.1 (main):0 > user=User.new(credentials: {a: 1})
  Generate Data Key (6306.1ms)  Context: {}
=> #<User:0x00007f83a24d4568> {
                         "created_at" => nil,
           "encrypted_credentials" => {},
        "encrypted_credentials_iv" => "0S9maHL9RkllY3JG\n",
                  "encrypted_kms_key" => "AQIDAHgAgmDwl7ioafhaCK6eJz6Sy/fneHh/yk9Uohq6mG
                        "ftp_enabled" => nil,
                        "health_plan" => nil,
           "hide_benefit_pay_amounts" => false,
                     "credentials" => nil,
                "poc_display_name" => nil,
2.5.1 (main):0 > user.credentials
=> {
  :a => 1
}
2.5.1 (main):0 > user.save(validate: false)
   (0.3ms)  BEGIN
  User Create (10.9ms)  INSERT
  INTO
    "users" (
      "created_at"
      ,"updated_at"
      ,"encrypted_credentials"
      ,"encrypted_credentials_iv"
      ,"encrypted_kms_key"
    )
  VALUES (
    $1
    ,$2
    ,$3
    ,$4
    ,$5
    ,$6
  ) RETURNING "id"  [["created_at", "2018-06-04 09:38:36.984295"], ["updated_at", "2018-06-04 09:38:36.984295"], ["encrypted_credentials", ""], ["encrypted_credentials_iv", "0S9maHL9RkllY3JG\n"], ["encrypted_kms_key", "AQIDAHgAgmDwl7ioafhaCK6eJz6Sy/fneHh/yk9Uohq6mGdsxwG+w4SOihUm\n5ED/eAg4TfnNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEH\nATAeBglghkgBZQMEAS4wEQQMYw4goISn37vGglLNAgEQgDtKnCfWNOBxDOQy\nAKOb+TYC8TWB9CFOvw0AFKI9Q2w7v4ARJy6I6B0VtcyYQtO9q8p9n+4bZNZn\nyc8Dbg==\n"]]
   (3.6ms)  COMMIT
=> true
2.5.1 (main):0 > user.credentials
=> {
  :a => 1
}
2.5.1 (main):0 > user.id
=> 49
2.5.1 (main):0 > user=User.find(49)
  User Load (3.3ms)  SELECT
    "users" . *
  FROM
    "users"
  WHERE
    "users" . "id" = $1 LIMIT $2  [["id", 49], ["LIMIT", 1]]
=> #<User:0x00007f83a13eeff0> {
                         "created_at" => Mon, 04 Jun 2018 09:38:36 UTC +00:00,
           "encrypted_credentials" => {},
        "encrypted_credentials_iv" => "0S9maHL9RkllY3JG\n",
                  "encrypted_kms_key" => "AQIDAHgAgmDwl7ioafhaCK6eJz6Sy/fneHh/yk9Uohq6mGdsxwG+w4SOihUm\n5ED/eAg4TfnNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEH\nATAeBglghkgB
2.5.1 (main):0 > user.credentials
  Decrypt Data Key (7993.3ms)  Context: {}
Seahorse::Client::NetworkingError: execution expired
from /Users/zoras/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
2.5.1 (main):0 > user.credentials
  Decrypt Data Key (2117.0ms)  Context: {}
NoMethodError: undefined method `unpack' for {}:Hash
from /Users/zoras/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:239:in `decrypt'
2.5.1 (main):0 > user.credentials
NoMethodError: undefined method `unpack' for {}:Hash
from /Users/zoras/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:239:in `decrypt'
2.5.1 (main):0 > user=User.find(49)
2.5.1 (main):0 > user.credentials
  Decrypt Data Key (1149.6ms)  Context: {}
NoMethodError: undefined method `unpack' for {}:Hash
from /Users/zoras/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:239:in `decrypt'
2.5.1 (main):0 >
```

**Comment by ankane** [comment]
Hey @zoras, glad AWS permissions are working. I haven't tried to encrypt an hstore column, but don't think it's related to KMS.

**Comment by zoras** [comment]
For anyone else stumbling on this issue, I managed to work around this by converting the column type from `hstore` to `jsonb` which seems to work pretty well.
